[project]
name = "dbt-iceberg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core==1.9.9",
    "duckdb==1.4.2",
    "dbt-duckdb==1.9.6",
    "dbt-fivetran==0.0.33",
    "pyiceberg[pyarrow]>=0.8.0",
]
